-- DuckDB session bootstrap (duckdb-skills pattern).
-- Usage from repo root:
--   duckdb -init analytics/state.sql duckdb/open_swe.duckdb
--
-- Or after: uv run python scripts/duckdb_init.py

-- Paths + resource limits generated by: uv run python scripts/duckdb_init.py
.read analytics/state.local.sql

-- Project default: 4GB memory cap (also set in scripts/duckdb_session.py)
.mode duckbox
.timer on

SELECT 'Attached open_swe.duckdb — try: SELECT * FROM traces LIMIT 5;' AS hint;
