-- DuckDB session bootstrap (duckdb-skills pattern).
-- Usage from repo root:
--   duckdb -init analytics/state.sql duckdb/open_swe.duckdb
--
-- Or after: uv run python scripts/duckdb_init.py

-- Paths are generated by: uv run python scripts/duckdb_init.py
.read analytics/state.local.sql

-- Helpful defaults for interactive exploration
.mode duckbox
.timer on

SELECT 'Attached open_swe.duckdb — try: SELECT * FROM traces LIMIT 5;' AS hint;
