#!/usr/bin/env python3
"""Rebuild the ``environment/src`` trees that ``reclaim_disk.py`` removed.

The recipe, in order, and every step matters:

1. Copy ``/app`` out of ``ladder-base:<repo>`` - the PRISTINE tree (bug absent).
2. Reverse-apply ``patches/gold.patch`` - gold turns excised into pristine, so
   its reverse turns pristine back into excised (bug present).
3. Delete the paths in the manifest's ``excision_deleted``. This step is why the
   manifest exists: an excision that removed in-tree ``*_test.go`` files leaves
   gold.patch with nothing to say about them, so after step 2 they are still
   there and the tree would not match what the verifier proved the suite against.
4. Verify the rebuilt file count against the manifest before declaring success.

A unit whose ``gold.patch`` was regenerated by a contract repair AFTER its tree was
staged cannot be rebuilt this way: gold no longer describes the distance between that
tree and pristine. ``--check`` reports how many reclaimed units are in that state
without writing anything, so the reversibility claim is a measurement rather than an
assumption. Any failure leaves the tree absent rather than half-built.

Usage::

    restore_env_src.py <unit-dir> [<unit-dir> ...]
    restore_env_src.py --check          # can every reclaimed unit be rebuilt?
    restore_env_src.py --sweep experiments/dose_response/sweep_kops3
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parents[2]


def pristine_copy(image: str, dest: pathlib.Path) -> bool:
    """Extract the image's /app once; callers reuse it across a whole sweep."""
    cid = subprocess.run(["docker", "create", image], capture_output=True,
                         text=True).stdout.strip()
    if not cid:
        return False
    try:
        r = subprocess.run(["docker", "cp", f"{cid}:/app/.", str(dest)],
                           capture_output=True, text=True)
        return r.returncode == 0
    finally:
        subprocess.run(["docker", "rm", cid], capture_output=True)


def count_files(root: pathlib.Path) -> int:
    """Regular files, symlinks excluded - the same definition the manifest was written
    with (``find . -type f``).

    ``rglob("*") + is_file()`` follows symlinks and counts the ones that resolve, so on
    helm - 5 symlinks under internal/third_party/dep/fs/testdata - a correct restore
    came out one to two files over and was rejected and deleted as a failure.
    """
    n = 0
    for dirpath, _dirs, files in os.walk(root, followlinks=False):
        for f in files:
            if not os.path.islink(os.path.join(dirpath, f)):
                n += 1
    return n


def excision_patch(unit: pathlib.Path) -> pathlib.Path | None:
    """The authored unit's excision patch, if its source survived.

    This is the CANONICAL construction: stage_units builds environment/src by applying
    excision.patch forward onto the base image's /app, and that is the tree the verifier
    proved the suite against. Reverse-applying gold is the older recipe and is wrong
    wherever an excision deleted files gold never restores.
    """
    base = unit.name.rsplit("-L", 1)[0]
    for cand in REPO.glob(f"experiments/pipeline/authored*/*/{base}/_author/excised/excision.patch"):
        return cand
    return None


def restore_from_excision(unit: pathlib.Path, env_src: pathlib.Path,
                          pristine: pathlib.Path, man: dict) -> str | None:
    patch = excision_patch(unit)
    if patch is None:
        return "no authored excision patch"
    shutil.rmtree(env_src, ignore_errors=True)
    env_src.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(pristine, env_src, symlinks=True)
    r = subprocess.run(["git", "apply", "--whitespace=nowarn", str(patch.resolve())],
                       cwd=env_src, capture_output=True, text=True)
    if r.returncode != 0:
        shutil.rmtree(env_src, ignore_errors=True)
        return f"excision patch did not apply ({(r.stderr or '').strip()[:70]})"
    have = count_files(env_src)
    want = man.get("file_count")
    if want is not None and have != want:
        shutil.rmtree(env_src, ignore_errors=True)
        return f"excision gave {have} files, manifest says {want}"
    return None


def sibling_tree(unit: pathlib.Path) -> pathlib.Path | None:
    """Another staged rung of the same unit whose tree survived.

    Rungs of one unit share the excised tree; only the instruction and which hidden
    tests are restored differ. So a surviving L0 or L5 IS this unit's tree, exactly,
    and copying it needs no patch to apply cleanly. That matters because 86 units
    cannot be rebuilt from gold at all - their gold.patch was regenerated by a
    contract repair after the tree was staged.
    """
    base = unit.name.rsplit("-L", 1)[0]
    for cand in sorted(unit.parent.parent.glob(f"*/{base}-L*")):
        if cand == unit or (cand / ".reclaimed.json").is_file():
            continue
        src = cand / "environment" / "src"
        if src.is_dir() and any(src.iterdir()):
            return src
    return None


def restore_from_sibling(unit: pathlib.Path, env_src: pathlib.Path, man: dict) -> str | None:
    """-> None on success, or a reason it was not usable."""
    sib = sibling_tree(unit)
    if sib is None:
        return "no sibling tree"
    shutil.rmtree(env_src, ignore_errors=True)
    env_src.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(sib, env_src, symlinks=True)
    # A rung >= L5 has hidden tests restored INTO the tree; the excised tree has none.
    # Removing every hidden relpath is a no-op for the lower rungs and exact for the
    # higher ones, so one rule covers both.
    hidden_root = unit / "tests" / "hidden"
    if hidden_root.is_dir():
        for h in hidden_root.rglob("*"):
            if h.is_file():
                (env_src / h.relative_to(hidden_root)).unlink(missing_ok=True)
    have = count_files(env_src)
    want = man.get("file_count")
    if want is not None and have != want:
        shutil.rmtree(env_src, ignore_errors=True)
        return f"sibling gave {have} files, manifest says {want}"
    return None


def restore(unit: pathlib.Path, cache: dict[str, pathlib.Path]) -> str:
    stamp = unit / ".reclaimed.json"
    env_src = unit / "environment" / "src"
    if env_src.is_dir() and any(env_src.iterdir()):
        return "skip: already present"
    if not stamp.is_file():
        # No manifest and no tree. That is a unit whose stamp was consumed by a restore
        # that then failed its own check, and it is the worst state to be in: nothing
        # left on disk says how to rebuild it. A sibling rung still does, so try that
        # rather than declaring the unit unrecoverable.
        if sibling_tree(unit) is None:
            return "skip: not reclaimed"
        why = restore_from_sibling(unit, env_src, {})
        return f"ok from sibling, no manifest ({count_files(env_src)} files)" if why is None \
            else f"FAIL: {why}"
    man = json.loads(stamp.read_text())
    image = man["base_image"]

    # Cheapest and most exact first: another rung of this same unit that still has its
    # tree. No image extraction, no patch, nothing to fail to apply.
    why = restore_from_sibling(unit, env_src, man)
    if why is None:
        stamp.unlink()
        return f"ok from sibling ({man.get('file_count')} files)"

    if image not in cache:
        tmp = pathlib.Path(tempfile.mkdtemp(prefix="pristine-"))
        if not pristine_copy(image, tmp):
            return f"FAIL: cannot extract {image}"
        cache[image] = tmp

    # Canonical next: pristine + excision.patch FORWARD, which is how stage_units built
    # the tree in the first place. Only then the gold-reverse fallback.
    why2 = restore_from_excision(unit, env_src, cache[image], man)
    if why2 is None:
        stamp.unlink()
        return f"ok from excision patch ({count_files(env_src)} files)"

    env_src.parent.mkdir(parents=True, exist_ok=True)
    shutil.rmtree(env_src, ignore_errors=True)
    shutil.copytree(cache[image], env_src, symlinks=True)

    gold = (unit / "patches" / "gold.patch").resolve()
    # git apply first: gold.patch was produced by git, and `patch` will happily apply
    # what it can and leave .rej/.orig behind, which looks like a populated tree and is
    # not one. Either way a failure must leave NOTHING, or the next caller sees a
    # half-built src and trusts it.
    err = None
    for cmd in (["git", "apply", "-R", "--whitespace=nowarn", str(gold)],
                ["patch", "-p1", "-R", "--silent", "--no-backup-if-mismatch",
                 "-r", "-", "-i", str(gold)]):
        r = subprocess.run(cmd, cwd=env_src, capture_output=True, text=True)
        rejects = list(env_src.rglob("*.rej")) + list(env_src.rglob("*.orig"))
        if r.returncode == 0 and not rejects:
            err = None
            break
        err = (r.stderr or r.stdout).strip().splitlines()[:1]
        err = err[0][:100] if err else f"{cmd[0]} left {len(rejects)} reject(s)"
        # start clean for the next attempt
        shutil.rmtree(env_src, ignore_errors=True)
        shutil.copytree(cache[image], env_src, symlinks=True)
    if err is not None:
        shutil.rmtree(env_src, ignore_errors=True)
        return f"FAIL: gold does not reverse onto pristine ({err})"

    for rel in man.get("excision_deleted", []):
        (env_src / rel).unlink(missing_ok=True)

    have = count_files(env_src)
    want = man.get("file_count")
    if want is not None and have != want:
        shutil.rmtree(env_src, ignore_errors=True)
        return f"FAIL: rebuilt {have} files, manifest says {want}"
    stamp.unlink()
    return f"ok ({have} files)"


def check_all() -> int:
    """Dry-run every reclaimed unit: does its gold.patch still reverse onto pristine?

    Uses ``git apply --check``, which writes nothing, against one extracted copy of each
    base image. A unit repaired after staging fails here — that is the answer, not a bug.
    """
    stamps = sorted((REPO / "experiments").rglob(".reclaimed.json"))
    print(f"reclaimed units: {len(stamps)}")
    cache: dict[str, pathlib.Path] = {}
    ok = bad = 0
    routes: dict[str, int] = {}
    per_image: dict[str, list[int]] = {}
    try:
        for st in stamps:
            unit = st.parent
            man = json.loads(st.read_text())
            image = man["base_image"]
            if image not in cache:
                tmp = pathlib.Path(tempfile.mkdtemp(prefix="pristine-"))
                if not pristine_copy(image, tmp):
                    print(f"  cannot extract {image}")
                    continue
                cache[image] = tmp
            # Two independent routes. A unit only counts as stuck when NEITHER works;
            # reporting the gold route alone called 86 units unrecoverable while a
            # sibling rung of the same unit was sitting there holding the tree.
            if sibling_tree(unit) is not None:
                good, via = True, "sibling"
            elif (ex := excision_patch(unit)) is not None and subprocess.run(
                    ["git", "apply", "--check", "--whitespace=nowarn", str(ex.resolve())],
                    cwd=cache[image], capture_output=True).returncode == 0:
                good, via = True, "excision"
            else:
                gold = unit / "patches" / "gold.patch"
                good = gold.is_file() and subprocess.run(
                    ["git", "apply", "-R", "--check", "--whitespace=nowarn",
                     str(gold.resolve())],
                    cwd=cache[image], capture_output=True).returncode == 0
                via = "gold" if good else "stuck"
            routes[via] = routes.get(via, 0) + 1
            ok, bad = ok + good, bad + (not good)
            per_image.setdefault(image, [0, 0])[0 if good else 1] += 1
    finally:
        for tmp in cache.values():
            shutil.rmtree(tmp, ignore_errors=True)
    print(f"  rebuildable      {ok}   " +
          ", ".join(f"{v} via {k}" for k, v in sorted(routes.items()) if k != "stuck"))
    print(f"  NOT rebuildable  {bad}")
    for img, (g, b) in sorted(per_image.items()):
        print(f"    {img:28s} {g:4d} ok  {b:4d} stuck")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("units", nargs="*")
    ap.add_argument("--sweep", help="restore every reclaimed unit in a sweep dir")
    ap.add_argument("--check", action="store_true",
                    help="report which reclaimed units can actually be rebuilt")
    args = ap.parse_args()

    if args.check:
        return check_all()

    units = [pathlib.Path(u) for u in args.units]
    if args.sweep:
        units += sorted(p.parent for p in pathlib.Path(args.sweep).glob("*/.reclaimed.json"))
    if not units:
        ap.error("nothing to restore")

    cache: dict[str, pathlib.Path] = {}
    bad = 0
    try:
        for u in units:
            res = restore(u, cache)
            bad += res.startswith("FAIL")
            print(f"{res:40s}  {u}")
    finally:
        for tmp in cache.values():
            shutil.rmtree(tmp, ignore_errors=True)
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
