#!/usr/bin/env python3
"""Rebuild the ``environment/src`` trees that ``reclaim_disk.py`` removed.

The recipe, in order, and every step matters:

1. Copy ``/app`` out of ``ladder-base:<repo>`` - the PRISTINE tree (bug absent).
2. Reverse-apply ``patches/gold.patch`` - gold turns excised into pristine, so
   its reverse turns pristine back into excised (bug present).
3. Delete the paths in the manifest's ``excision_deleted``. This step is why the
   manifest exists: an excision that removed in-tree ``*_test.go`` files leaves
   gold.patch with nothing to say about them, so after step 2 they are still
   there and the tree would not match what the verifier proved the suite against.
4. Verify the rebuilt file count against the manifest before declaring success.

A unit whose ``gold.patch`` was regenerated by a contract repair AFTER its tree was
staged cannot be rebuilt this way: gold no longer describes the distance between that
tree and pristine. ``--check`` reports how many reclaimed units are in that state
without writing anything, so the reversibility claim is a measurement rather than an
assumption. Any failure leaves the tree absent rather than half-built.

Usage::

    restore_env_src.py <unit-dir> [<unit-dir> ...]
    restore_env_src.py --check          # can every reclaimed unit be rebuilt?
    restore_env_src.py --sweep experiments/dose_response/sweep_kops3
"""

from __future__ import annotations

import argparse
import json
import pathlib
import shutil
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parents[2]


def pristine_copy(image: str, dest: pathlib.Path) -> bool:
    """Extract the image's /app once; callers reuse it across a whole sweep."""
    cid = subprocess.run(["docker", "create", image], capture_output=True,
                         text=True).stdout.strip()
    if not cid:
        return False
    try:
        r = subprocess.run(["docker", "cp", f"{cid}:/app/.", str(dest)],
                           capture_output=True, text=True)
        return r.returncode == 0
    finally:
        subprocess.run(["docker", "rm", cid], capture_output=True)


def restore(unit: pathlib.Path, cache: dict[str, pathlib.Path]) -> str:
    stamp = unit / ".reclaimed.json"
    if not stamp.is_file():
        return "skip: not reclaimed"
    env_src = unit / "environment" / "src"
    if env_src.is_dir() and any(env_src.iterdir()):
        return "skip: already present"
    man = json.loads(stamp.read_text())
    image = man["base_image"]

    if image not in cache:
        tmp = pathlib.Path(tempfile.mkdtemp(prefix="pristine-"))
        if not pristine_copy(image, tmp):
            return f"FAIL: cannot extract {image}"
        cache[image] = tmp

    env_src.parent.mkdir(parents=True, exist_ok=True)
    shutil.rmtree(env_src, ignore_errors=True)
    shutil.copytree(cache[image], env_src, symlinks=True)

    gold = (unit / "patches" / "gold.patch").resolve()
    # git apply first: gold.patch was produced by git, and `patch` will happily apply
    # what it can and leave .rej/.orig behind, which looks like a populated tree and is
    # not one. Either way a failure must leave NOTHING, or the next caller sees a
    # half-built src and trusts it.
    err = None
    for cmd in (["git", "apply", "-R", "--whitespace=nowarn", str(gold)],
                ["patch", "-p1", "-R", "--silent", "--no-backup-if-mismatch",
                 "-r", "-", "-i", str(gold)]):
        r = subprocess.run(cmd, cwd=env_src, capture_output=True, text=True)
        rejects = list(env_src.rglob("*.rej")) + list(env_src.rglob("*.orig"))
        if r.returncode == 0 and not rejects:
            err = None
            break
        err = (r.stderr or r.stdout).strip().splitlines()[:1]
        err = err[0][:100] if err else f"{cmd[0]} left {len(rejects)} reject(s)"
        # start clean for the next attempt
        shutil.rmtree(env_src, ignore_errors=True)
        shutil.copytree(cache[image], env_src, symlinks=True)
    if err is not None:
        shutil.rmtree(env_src, ignore_errors=True)
        return f"FAIL: gold does not reverse onto pristine ({err})"

    for rel in man.get("excision_deleted", []):
        (env_src / rel).unlink(missing_ok=True)

    have = sum(1 for _ in env_src.rglob("*") if _.is_file())
    want = man.get("file_count")
    if want is not None and have != want:
        shutil.rmtree(env_src, ignore_errors=True)
        return f"FAIL: rebuilt {have} files, manifest says {want}"
    stamp.unlink()
    return f"ok ({have} files)"


def check_all() -> int:
    """Dry-run every reclaimed unit: does its gold.patch still reverse onto pristine?

    Uses ``git apply --check``, which writes nothing, against one extracted copy of each
    base image. A unit repaired after staging fails here — that is the answer, not a bug.
    """
    stamps = sorted((REPO / "experiments").rglob(".reclaimed.json"))
    print(f"reclaimed units: {len(stamps)}")
    cache: dict[str, pathlib.Path] = {}
    ok = bad = 0
    per_image: dict[str, list[int]] = {}
    try:
        for st in stamps:
            unit = st.parent
            man = json.loads(st.read_text())
            image = man["base_image"]
            if image not in cache:
                tmp = pathlib.Path(tempfile.mkdtemp(prefix="pristine-"))
                if not pristine_copy(image, tmp):
                    print(f"  cannot extract {image}")
                    continue
                cache[image] = tmp
            gold = unit / "patches" / "gold.patch"
            good = gold.is_file() and subprocess.run(
                ["git", "apply", "-R", "--check", "--whitespace=nowarn", str(gold.resolve())],
                cwd=cache[image], capture_output=True).returncode == 0
            ok, bad = ok + good, bad + (not good)
            per_image.setdefault(image, [0, 0])[0 if good else 1] += 1
    finally:
        for tmp in cache.values():
            shutil.rmtree(tmp, ignore_errors=True)
    print(f"  rebuildable      {ok}")
    print(f"  NOT rebuildable  {bad}")
    for img, (g, b) in sorted(per_image.items()):
        print(f"    {img:28s} {g:4d} ok  {b:4d} stuck")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("units", nargs="*")
    ap.add_argument("--sweep", help="restore every reclaimed unit in a sweep dir")
    ap.add_argument("--check", action="store_true",
                    help="report which reclaimed units can actually be rebuilt")
    args = ap.parse_args()

    if args.check:
        return check_all()

    units = [pathlib.Path(u) for u in args.units]
    if args.sweep:
        units += sorted(p.parent for p in pathlib.Path(args.sweep).glob("*/.reclaimed.json"))
    if not units:
        ap.error("nothing to restore")

    cache: dict[str, pathlib.Path] = {}
    bad = 0
    try:
        for u in units:
            res = restore(u, cache)
            bad += res.startswith("FAIL")
            print(f"{res:40s}  {u}")
    finally:
        for tmp in cache.values():
            shutil.rmtree(tmp, ignore_errors=True)
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
