"""Pipeline extensions the overnight orchestrator calls.

Independent of ``openswe_traces.pipeline`` (another builder owns that package).
"""

from openswe_traces.pipeline_ext.author_meta import (
    PREDICTED_FLIP_LINE_RE,
    AuthorCalibration,
    AuthorUnit,
    PredictedFlip,
    author_calibration,
    parse_author_dir,
    parse_difficulty_md,
    parse_predicted_flip,
    predicted_flip_line,
)
from openswe_traces.pipeline_ext.calibration import (
    AttemptRecord,
    CalibrationReport,
    EarlyWarning,
    attempt_from_dict,
    calibrate,
    early_warning_flags,
    inter_attempt_agreement,
    nearest_50,
    pass_rate_curve,
)
from openswe_traces.pipeline_ext.controls import (
    ControlStatus,
    UnitMeta,
    control_status,
    is_control,
    pick_control,
)
from openswe_traces.pipeline_ext.hack_audit import (
    AUDIT_HIDDEN_SEED,
    DEFAULT_HIDDEN_SEED,
    HIDDEN_SEED_ENV,
    HackVerdict,
    allowlist_violations,
    audit_passing_attempt,
    extract_literals,
    parse_touched_paths,
    scan_trajectory,
)
from openswe_traces.pipeline_ext.ladder_policy import (
    CLIMB_ORDER,
    FlipEvidence,
    FlipResult,
    LadderAction,
    LevelAttempt,
    TaskState,
    attempts_from_pairs,
    flip_point,
    next_actions,
)
from openswe_traces.pipeline_ext.timeouts import (
    TIMEOUT_CLASS,
    TimeoutBudget,
    agent_timeout_sec,
    classify_attempt,
    counts_as_failure,
    poll_interval_sec,
    session_timeout_sec,
    timeout_budget,
)

__all__ = [
    "AUDIT_HIDDEN_SEED",
    "CLIMB_ORDER",
    "DEFAULT_HIDDEN_SEED",
    "HIDDEN_SEED_ENV",
    "PREDICTED_FLIP_LINE_RE",
    "TIMEOUT_CLASS",
    "AttemptRecord",
    "AuthorCalibration",
    "AuthorUnit",
    "CalibrationReport",
    "ControlStatus",
    "EarlyWarning",
    "FlipEvidence",
    "FlipResult",
    "HackVerdict",
    "LadderAction",
    "LevelAttempt",
    "PredictedFlip",
    "TaskState",
    "TimeoutBudget",
    "UnitMeta",
    "agent_timeout_sec",
    "allowlist_violations",
    "attempt_from_dict",
    "attempts_from_pairs",
    "audit_passing_attempt",
    "author_calibration",
    "calibrate",
    "classify_attempt",
    "control_status",
    "counts_as_failure",
    "early_warning_flags",
    "extract_literals",
    "flip_point",
    "inter_attempt_agreement",
    "is_control",
    "nearest_50",
    "next_actions",
    "parse_author_dir",
    "parse_difficulty_md",
    "parse_predicted_flip",
    "parse_touched_paths",
    "pass_rate_curve",
    "pick_control",
    "poll_interval_sec",
    "predicted_flip_line",
    "scan_trajectory",
    "session_timeout_sec",
    "timeout_budget",
]
